### ISSUE TITLE
Can't execute the app on OSX 10.12.1

### ISSUE THREAD

**Issue by luispigu** [zydeco/TouchBarServer#1]
Hi,
First of all, thank you for developing this cool app.

When i executed TouchBarServer on my mac.
I got below error message.
<img width="532" alt="2016-11-06 11 16 19" src="https://cloud.githubusercontent.com/assets/1230159/20034892/f5d4a06e-a412-11e6-983a-a4c9dda72fa6.png">

But I'm using Mac OSX version 10.12.1 latest.
<img width="443" alt="2016-11-06 11 16 32" src="https://cloud.githubusercontent.com/assets/1230159/20034894/fb31212c-a412-11e6-8407-52d856a56c88.png">

How can i use TouchBarServer?
Should i wait next OSX version or beta version?

Thanks,
Luis

**Comment by mblsha** [comment]
You've got a slightly older build. Get a new one from here: https://support.apple.com/kb/dl1897

**Comment by luispigu** [comment]
Hi, @mblsha 
No, I checked the url which you wrote, it is same with mine.

Thanks

**Comment by mblsha** [comment]
You need to click on the version number label that's below "macOS Sierra" to see the build number (it doesn't look like it but it's clickable). Yours is probably lower than required and doesn't have the built-in Touch Bar support.

**Comment by luispigu** [comment]
Thanks @mblsha.
I found that build number on my OSX was 16B2555.
After i installed latest version, i can execute TouchBarServer.

Thank you.

**Comment by zydeco** [comment]
thanks @mblsha 👍
